name: Conda

on:
  workflow_dispatch:
  push:
    branches:
      - latest
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-2016]
        python-version: ["3.6", "3.8"]

    runs-on: ${{ matrix.platform }}

    # The setup-miniconda action needs this to activate miniconda
    defaults:
      run:
        shell: "bash -l {0}"

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
          submodules: recursive

      - name: Get conda
        uses: conda-incubator/setup-miniconda@v2.0.0
        with:
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
          channel-priority: strict

      - name: Prepare
        run: conda install conda-build conda-verify

      - name: Build
        run: conda build conda.recipe

      - name: Install
        run: conda install -c ${CONDA_PREFIX}/conda-bld/ pyasge

      - name: Test
        run: python tests/test.py
