name: Wheels

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - latest
  release:
    types:
      - published

env:
  CIBW_TEST_COMMAND: python {project}/tests/test.py
  CIBW_MANYLINUX_X86_64_IMAGE: registry.gitlab.com/huxyuk/manylinux/x64-asge
  CIBW_MANYLINUX_I686_IMAGE: registry.gitlab.com/huxyuk/manylinux/i686-asge

jobs:
  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
          submodules: recursive

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.8'

      - name: Build sdist
        run: python setup.py sdist

      - uses: actions/upload-artifact@v2
        with:
          path: dist/*.tar.gz

  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-10.15]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
          submodules: recursive

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.8'

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.2.2
        env:
          CIBW_BUILD: cp3*-*
          CIBW_ARCHS_MACOS: x86_64
          CIBW_SKIP: "*-musllinux_*"

      - name: Show files
        run: ls -lh wheelhouse
        shell: bash

      - name: Verify clean directory
        run: git diff --exit-code
        shell: bash

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

#  upload_all:
#    name: Upload if release
#    needs: [build_wheels, build_sdist]
#    runs-on: ubuntu-latest
#    if: github.event_name == 'release' && github.event.action == 'published'
#
#    steps:
#    - uses: actions/setup-python@v2
#
#    - uses: actions/download-artifact@v2
#      with:
#        name: artifact
#        path: dist
#
#    - uses: pypa/gh-action-pypi-publish@v1.4.1
#      with:
#        user: __token__
#        password: ${{ secrets.pypi_password }}
